In [3]:
import tensorflow as tf
from keras import layers
from tensorflow.keras.datasets import mnist
import numpy as np

In [ ]:
(x_train,y_train), (x_test,y_test) = mnist.load_data()
x_train = x_train.reshape(-1,28,28,1).astype("float32") / 255.0
x_test = x_test.reshape(-1,28,28,1).astype("float32") / 255.0

In [10]:
vgg = tf.keras.applications.VGG19(include_top = False,weights = "imagenet")

In [11]:
for idx,layer in enumerate(vgg.layers):
    print(idx,layer)

0 <keras.engine.input_layer.InputLayer object at 0x000002181DBBBC40>
1 <keras.layers.convolutional.Conv2D object at 0x000002181DBBB9A0>
2 <keras.layers.convolutional.Conv2D object at 0x000002181DBBB7C0>
3 <keras.layers.pooling.MaxPooling2D object at 0x000002181DD15640>
4 <keras.layers.convolutional.Conv2D object at 0x000002181DD15C70>
5 <keras.layers.convolutional.Conv2D object at 0x000002181DBAAF70>
6 <keras.layers.pooling.MaxPooling2D object at 0x000002181D78F880>
7 <keras.layers.convolutional.Conv2D object at 0x000002181DB68E20>
8 <keras.layers.convolutional.Conv2D object at 0x000002181DB9ACD0>
9 <keras.layers.convolutional.Conv2D object at 0x000002181DB71970>
10 <keras.layers.convolutional.Conv2D object at 0x000002181DD1ED00>
11 <keras.layers.pooling.MaxPooling2D object at 0x000002181DB933D0>
12 <keras.layers.convolutional.Conv2D object at 0x000002181DD1AD90>
13 <keras.layers.convolutional.Conv2D object at 0x000002181DD25E20>
14 <keras.layers.convolutional.Conv2D object at 0x000002

In [9]:
vgg.trainable = False
for idx,l in enumerate(vgg.layers):
    print(idx , l)

0 <keras.engine.input_layer.InputLayer object at 0x0000021856436A30>
1 <keras.layers.convolutional.Conv2D object at 0x000002181D73EBB0>
2 <keras.layers.convolutional.Conv2D object at 0x000002181D78F1F0>
3 <keras.layers.pooling.MaxPooling2D object at 0x000002181D7FE6A0>
4 <keras.layers.convolutional.Conv2D object at 0x000002181D7FE160>
5 <keras.layers.convolutional.Conv2D object at 0x000002181DB68250>
6 <keras.layers.pooling.MaxPooling2D object at 0x000002181DB68820>
7 <keras.layers.convolutional.Conv2D object at 0x000002181DB68CA0>
8 <keras.layers.convolutional.Conv2D object at 0x000002181DB75880>
9 <keras.layers.convolutional.Conv2D object at 0x000002181DB7A940>
10 <keras.layers.convolutional.Conv2D object at 0x000002181DB75D60>
11 <keras.layers.pooling.MaxPooling2D object at 0x000002181DB849A0>
12 <keras.layers.convolutional.Conv2D object at 0x000002181DB8B070>
13 <keras.layers.convolutional.Conv2D object at 0x000002181DB8B1F0>
14 <keras.layers.convolutional.Conv2D object at 0x000002

In [4]:
x = tf.io.read_file("../images/13192.jpg")
x = tf.io.decode_image(x)
x = tf.expand_dims(x,axis = 0)
x = tf.cast(x,tf.float16)
l6 = x
l7 = x

In [39]:
for l in vgg.layers[:6]:
    l6 = l(l6)

In [40]:
l6.shape , l7.shape

(TensorShape([1, 540, 960, 128]), TensorShape([1, 270, 480, 128]))

In [3]:
from losses import vgg22

In [5]:
loss = vgg22()
loss(x,x)

<tf.Tensor: shape=(1, 540, 960), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>

In [5]:
from losses import vgg54
loss = vgg54()
loss(x,x)

<tf.Tensor: shape=(1, 67, 120), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>